version: "3"

services:
  backup_automation:
    container_name: backup_automation
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - ./config.yaml:/srv/config.yaml:ro
        - ./secrets.yaml:/srv/secrets.yaml:ro
        - ./ssh_key.key:/srv/ssh_keys/ssh_key.key:ro
        - ./gpg_key.key:/srv/gpg_keys/gpg_key.key:ro
        - ./trustdb.txt:/srv/trustdb.txt:ro
    environment:
        - LOG_LEVEL=INFO
        - BACKUP_DELAY_IN_SECONDS=61
    restart: always
