version: "3"

services:
  backup_automation:
    container_name: backup_automation
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - ./config.yaml:/srv/config.yaml:ro
        - ./secrets.yaml:/srv/secrets.yaml:ro
        - ./backup_automation_ssh.key:/srv/ssh_keys/ssh_key.key:ro
        - ./backup_automation_gpg.key:/srv/gpg_keys/gpg_key.key:ro
    environment:
        - LOG_LEVEL=DEBUG
        - BACKUP_DELAY_IN_SECONDS=61
    restart: always
